#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if npm run test:ci; then
    echo "Test: success!"
else
    echo "Test: failure!"
fi

if npm audit; then
    echo "Audit: success!"
else
    echo "Audit: failure!"
fi
